name: Generate rebuild summary
description: Generate rebuild gh command summary
inputs:
  inputs-json:
    default: "${{ toJson(github.event.inputs) }}"

runs:
  using: composite
  steps:
    - name: Create Gh CLI Command Summary
      shell: bash
      env:
        GH_COMMAND: gh workflow run --repo "${{ github.repository }}" --ref "${{ github.ref_name }}" --json
      run: |
        # Create Gh CLI Command Summary
        WORKFLOW_PATH=${{ github.event.workflow }}
        {
          echo '```sh'
          echo "echo '$(echo '${{ inputs.inputs-json }}' | jq -c)' | ${GH_COMMAND} \"${WORKFLOW_PATH##*/}\""
          echo '```'
        } >> "${GITHUB_STEP_SUMMARY}"
      if: github.event_name == 'workflow_dispatch'

